### ISSUE TITLE
Add information for BOM

### ISSUE THREAD

**Issue by lpatiny** [Hackuarium/bioreactor#46]
We will soon probably ask for a small production to elecrow

@andrescvargasr Could you check how to be able to create a BOM with manufacturer part and supplier part ?

Could you also complete the missing field to have the manufacturer part number and supplier part number for Mouser ?

The goal is to be able to create the BOM with all the required information to get PCBA.

**Comment by andrescvargasr** [comment]
There are some changes:

- C9, C10: They changed packages 1206 to 0805.
- D12: Change to SMA package due to availability.
- D6: It changes from WHITE LED to GREEN because it was the only one with that color and there was no apparent reason not to combine them with the other LEDs of different colors.
- Y1: A crystal with four connection points is selected because it has a greater tolerance than its 2-pin counterpart (it goes from 30 PPM to 20 PPM).

The following components are pending:
- J5, J11: Not available from Mouser or Digikey, but this audio jack available from Aliexpress via this link: https://www.aliexpress.com/item/33004214640.html?spm=a2g0s.9042311.0.0.6 efd4c4d7S5uUt
- Rlim: There is no set value in the design.
- U4: Not available from Mouser or Digikey, but this HX711 IC is available on Aliexpress via this link: https://www.aliexpress.com/item/33012086165.html?spm=a2g0s.9042311.0.0.6efd4c4d7S5uUt
